// Licensed to the LF AI & Data foundation under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <gtest/gtest.h>

#include <cmath>
#include <cstdint>
#include <milvus/thirdparty/nlohmann/json.hpp>
#include <string>
#include <vector>

#include "milvus/types/BloomFilter.h"

namespace {

// The blob is the whole contract: SDKs interoperate only if they emit the same bytes for the
// same members, because the server embeds the blob verbatim and never rebuilds the filter.
// These are the fixtures the Go SDK (client/sbbf/testdata) and the segcore C++ unit tests
// check themselves against, trimmed to the fields needed here. The last case was generated by
// Arrow C++'s own parquet::BlockSplitBloomFilter.
const char* kGoldenVectors =
    R"json({"cases":[{"name":"small_int64_set","fpr":0.001,"int_values":["-9223372036854775808","-1","0","1","2","42","1000000007","9223372036854775807"],"string_values":[],"blob_hex":"4d424631010001000800000000000000fca9f1d24d62503f01000000010000000117100a804845062834804200440612100448a40680089c4040542838410046"},{"name":"small_string_set","fpr":0.001,"int_values":[],"string_values":["","a","milvus","bloom","日本語","🚀🚀","hello world"],"blob_hex":"4d424631010001000700000000000000fca9f1d24d62503f010000000200000010002c24010e020492110042181000b08a40860000284209010114a8015410c0"},{"name":"mixed_int_string_fpr01","fpr":0.01,"int_values":["0","2654435760","10617743042","23889921846","42470972172","66360894020","95559687390","130067352282","169883888696","215009296632","265443576090","321186727070","382238749572","448599643596","520269409142","597248046210","679535554800","767131934912","860037186546","958251309702","1061774304380","1170606170580","1284746908302","1404196517546","1528954998312","1659022350600","1794398574410","1935083669742","2081077636596","2232380474972","2388992184870","2550912766290","2718142219232","2890680543696","3068527739682","3251683807190","3440148746220","3633922556772","3833005238846","4037396792442","4247097217560","4462106514200","4682424682362","4908051722046","5138987633252","5375232415980","5616786070230","5863648596002","6115819993296","6373300262112","6636089402450","6904187414310","7177594297692","7456310052596","7740334679022","8029668176970","8324310546440","8624261787432","8929521899946","9240090883982","9555968739540","9877155466620","10203651065222","10535455535346","10872568876992","11214991090160","11562722174850","11915762131062","12274110958796","12637768658052","13006735228830","13381010671130","13760594984952","14145488170296","14535690227162","14931201155550","15332020955460","15738149626892","16149587169846","16566333584322","16988388870320","17415753027840","17848426056882","18286407957446","18729698729532","19178298373140","19632206888270","20091424274922","20555950533096","21025785662792","21500929664010","21981382536750","22467144281012","22958214896796","23454594384102","23956282742930","24463279973280","24975586075152","25493201048546","26016124893462"],"string_values":["key-000","key-001","key-002","key-003","key-004","key-005","key-006","key-007","key-008","key-009","key-010","key-011","key-012","key-013","key-014","key-015","key-016","key-017","key-018","key-019","key-020","key-021","key-022","key-023","key-024","key-025","key-026","key-027","key-028","key-029","key-030","key-031","key-032","key-033","key-034","key-035","key-036","key-037","key-038","key-039","key-040","key-041","key-042","key-043","key-044","key-045","key-046","key-047","key-048","key-049","key-050","key-051","key-052","key-053","key-054","key-055","key-056","key-057","key-058","key-059","key-060","key-061","key-062","key-063","key-064","key-065","key-066","key-067","key-068","key-069","key-070","key-071","key-072","key-073","key-074","key-075","key-076","key-077","key-078","key-079","key-080","key-081","key-082","key-083","key-084","key-085","key-086","key-087","key-088","key-089","key-090","key-091","key-092","key-093","key-094","key-095","key-096","key-097","key-098","key-099"],"blob_hex":"4d42463101000100c8000000000000007b14ae47e17a843f08000000030000008b0e5453af3c940cc35a82ae1ae35d40adb67448579c407a6e23b083dadec8a1c7ceaacd948e57ad6d3e27897d93bc037eafc435718477d4c854779ed2f6c42f3a4dd247eedd533a3f66c8d0e982a37a06b873747ed53da91ee72d64b299bb5a0e8c939c2e0811f6de0f6981d534735812e62d5c6e0be23bcbd8e95430cdb4ceddf73cda2fbdb73bfb6f4bb7b7cc9effb6617f57677bbdecbbbf1eadee9b89fbe1abbe8af846956ebbd05f86b94a3aa9e1c9e84afa126753305a564ec2613ca31a750a8244f1241dc6a515f04cf56332c0ed70190e3397c00c8a3e1a091de1e2f5dadf3dd41effa96f276c5d3b89353d37b9dbf0c536a2ee3aae1eb7a3a57987"},{"name":"cpp_generated_100_int64","fpr":0.001,"int_values":["8658146177844533459","-714115857001785192","-711603746570640538","1856884651970074846","-6128308519697625279","-2589362387793879938","-6442563125466096028","750449894305379027","3111933325748673652","-8340557378279999415","3951922714928010113","6257617642960066290","-4932914836218115438","-254766811250723988","-972464704980193410","8343385803650447430","-5257084382003438550","-6616486918820683035","3083666357154710214","-5726888427991752578","-9128850143193775260","6047080612367723201","5010629517235799125","6204213050223697893","-6825047074474943286","61825490054885972","-4206432566372036212","-6384803002243357911","4781221566471024313","-6933572190204638413","-3755687601868290202","6103617627070083271","1928553730286442922","-8120696789570889969","199781238021055483","-2836650735854471874","-6060537595207524644","-2858979587650817160","6462857294646271753","6869965629052836347","-9143094082755825844","-3666958498711544120","2404560920011035252","-1830525602054026140","-3188057240838245030","193410819143160149","-3800685568035774702","-4477104209919868774","-8739613278692081631","-7579537075930282644","-2780624593535075628","4346378388827855824","3027400241487030817","7166223350348046442","-1404973300057389001","-4660460439065809128","4440578451885931377","-1602382980522755233","-8520999113949415644","522858582121026645","-7800091754642642219","-3920240576272088748","-5972087047270789639","-292822079884588537","5726679124197100871","6993342257917585484","-1507700027333334802","7625165405736523917","3871742148244963336","6732608290130115182","1037756568592031861","8938661400053168226","8074223581569335021","942866823242401439","8160816984695000015","-5932593205698779036","6514430052652417535","257336044342116846","-8850258025880686884","1305277040432704897","-8943724248689609293","9055329856683071325","8774664884879451119","7534849732070022111","6795686577940900372","-2457967626187998335","-4329442528735256807","6970150277175353033","1889972226793962337","-7469356818739105547","-1664176171929672829","2106315558160283243","-2118765057479439297","-6647605175104144115","-7883174218247532555","423810741545905895","-2259334501027694012","6535037028082780756","1693824344663462632","-4747800264152686457"],"string_values":[],"blob_hex":"4d424631010001006400000000000000fca9f1d24d62503f0800000001000000015601b9e004cc420700a0cbf8008e08c412c02895c55a4008c04fa2b38300130238701020130b222090c2202683401004181d4010032098a00024ac61c8904020281a40826a0432081542189270304089018e6000930ac15440508a60016249591073110e3074abd110ada1c1c7144b37e8804390a889e8043964f9b64d8002803214440480491254092188250c1003410149b075a00824840492c8314202a49649488a081324f10871339849c0095a74240f41581b4e494803c2390311071f0ad1222c915e4096a306bc2480d284b5a2c02c9a470121bad0e81cc9858e2304e02289744c880f20c0500a7451768282a550c83090a5270a8213ca89ca03006a"}]})json";

std::string
ToHex(const std::vector<uint8_t>& data) {
    static const char* kDigits = "0123456789abcdef";
    std::string out;
    out.reserve(data.size() * 2);
    for (auto byte : data) {
        out.push_back(kDigits[byte >> 4]);
        out.push_back(kDigits[byte & 0x0F]);
    }
    return out;
}

uint32_t
ReadU32LE(const std::vector<uint8_t>& blob, size_t offset) {
    return static_cast<uint32_t>(blob[offset]) | static_cast<uint32_t>(blob[offset + 1]) << 8 |
           static_cast<uint32_t>(blob[offset + 2]) << 16 | static_cast<uint32_t>(blob[offset + 3]) << 24;
}

}  // namespace

TEST(BloomFilterTest, MatchesSharedGoldenVectors) {
    auto fixture = nlohmann::json::parse(kGoldenVectors);
    ASSERT_EQ(4, fixture["cases"].size());

    for (const auto& one : fixture["cases"]) {
        const auto name = one["name"].get<std::string>();
        milvus::BloomFilterBuilder builder(one["int_values"].size() + one["string_values"].size(),
                                           one["fpr"].get<double>());
        for (const auto& value : one["int_values"]) {
            builder.AddInt64(std::stoll(value.get<std::string>()));
        }
        for (const auto& value : one["string_values"]) {
            builder.AddString(value.get<std::string>());
        }
        EXPECT_EQ(one["blob_hex"].get<std::string>(), ToHex(builder.Build())) << "golden vector " << name;
    }
}

TEST(BloomFilterTest, LaysOutTheEnvelopeHeader) {
    milvus::BloomFilterBuilder builder(1, 0.01);
    builder.AddInt64(42);
    auto blob = builder.Build();

    EXPECT_EQ("MBF1", std::string(reinterpret_cast<const char*>(blob.data()), 4));
    EXPECT_EQ(1, blob[4]);  // version, uint16 LE
    EXPECT_EQ(0, blob[5]);
    EXPECT_EQ(1, blob[6]);  // algo, uint16 LE
    EXPECT_EQ(0, blob[7]);
    EXPECT_EQ(1, blob[28]);  // domains: int64 only
    // Reserved bytes must be zero; the server rejects a blob that sets them.
    EXPECT_EQ(0, blob[29] | blob[30] | blob[31]);

    const auto num_blocks = ReadU32LE(blob, 24);
    EXPECT_EQ(blob.size() - 32, static_cast<size_t>(num_blocks) * 32);
    EXPECT_EQ(0u, num_blocks & (num_blocks - 1)) << "num_blocks must be a power of two";
    EXPECT_EQ(num_blocks, builder.NumBlocks());
}

TEST(BloomFilterTest, RecordsTheValueDomains) {
    milvus::BloomFilterBuilder integers(1, 0.001);
    EXPECT_EQ(1, integers.AddInt64(1).Domains());

    milvus::BloomFilterBuilder strings(1, 0.001);
    EXPECT_EQ(2, strings.AddString("a").Domains());

    // A builder may record both -- a JSON path can legitimately hold either type.
    milvus::BloomFilterBuilder mixed(2, 0.001);
    EXPECT_EQ(3, mixed.AddInt64(1).AddString("a").Domains());

    // An empty set records no domain, so the server skips the probe entirely and the filter
    // matches nothing rather than aliasing into whichever domain is probed.
    milvus::BloomFilterBuilder empty(0, 0.001);
    auto blob = empty.Build();
    EXPECT_EQ(0, blob[28]);
    EXPECT_EQ(32u + 32u, blob.size());
}

TEST(BloomFilterTest, BatchInsertMatchesOneAtATime) {
    std::vector<int64_t> numbers{-9223372036854775807LL - 1, -1, 0, 1, 42, 9223372036854775807LL};
    std::vector<std::string> words{"", "a", "milvus", "日本語", "🚀🚀"};

    milvus::BloomFilterBuilder one_by_one(numbers.size() + words.size(), 0.001);
    for (auto value : numbers) {
        one_by_one.AddInt64(value);
    }
    for (const auto& value : words) {
        one_by_one.AddString(value);
    }

    milvus::BloomFilterBuilder batched(numbers.size() + words.size(), 0.001);
    batched.AddInt64s(numbers).AddStrings(words);

    EXPECT_EQ(one_by_one.Build(), batched.Build());
}

TEST(BloomFilterTest, BuildsATemplateReadyBinaryValue) {
    nlohmann::json value;
    auto status = milvus::BloomFilterTemplate(std::vector<std::string>{"alice", "bob", "小明"}, 0.01, value);
    ASSERT_TRUE(status.IsOk()) << status.Message();

    // Binary, not a string: the filter body is not valid UTF-8, so a string round trip would
    // corrupt it as well as inflating it through base64.
    ASSERT_TRUE(value.is_binary());

    milvus::BloomFilterBuilder expected(3, 0.01);
    expected.AddStrings({"alice", "bob", "小明"});
    const auto& binary = value.get_binary();
    EXPECT_EQ(expected.Build(), std::vector<uint8_t>(binary.begin(), binary.end()));
}

TEST(BloomFilterTest, EstimateMatchesTheBuiltSize) {
    for (double fpr : {milvus::BloomFilterMinFPR, 0.001, milvus::BloomFilterDefaultFPR, milvus::BloomFilterMaxFPR}) {
        for (uint64_t count : {0, 1, 2, 100, 5000}) {
            uint64_t estimated = 0;
            auto status = milvus::EstimateBloomFilterSize(count, fpr, estimated);
            ASSERT_TRUE(status.IsOk()) << status.Message();

            std::vector<int64_t> members(count);
            for (uint64_t i = 0; i < count; i++) {
                members[i] = static_cast<int64_t>(i);
            }
            milvus::BloomFilterBuilder builder(count, fpr);
            builder.AddInt64s(members);
            EXPECT_EQ(estimated, builder.Build().size()) << "count=" << count << " fpr=" << fpr;
        }
    }

    // The estimate is what callers check against the proxy 64 MiB body limit, so the clamp at
    // the top end has to hold.
    uint64_t clamped = 0;
    ASSERT_TRUE(milvus::EstimateBloomFilterSize(1000000000000ULL, milvus::BloomFilterMinFPR, clamped).IsOk());
    EXPECT_EQ(32u + 128u * 1024u * 1024u, clamped);
}

TEST(BloomFilterTest, RejectsAnOutOfRangeRate) {
    for (double fpr : {0.00009, 0.051, 0.0, -1.0, std::nan("")}) {
        nlohmann::json value;
        EXPECT_FALSE(milvus::BloomFilterTemplate(std::vector<int64_t>{1}, fpr, value).IsOk()) << "fpr " << fpr;
        EXPECT_FALSE(milvus::BloomFilterTemplate(std::vector<std::string>{"a"}, fpr, value).IsOk()) << "fpr " << fpr;

        uint64_t size = 0;
        EXPECT_FALSE(milvus::EstimateBloomFilterSize(1, fpr, size).IsOk()) << "fpr " << fpr;
        EXPECT_THROW(milvus::BloomFilterBuilder(1, fpr), std::runtime_error) << "fpr " << fpr;
    }

    // Both boundaries are accepted.
    for (double fpr : {milvus::BloomFilterMinFPR, milvus::BloomFilterMaxFPR}) {
        nlohmann::json value;
        EXPECT_TRUE(milvus::BloomFilterTemplate(std::vector<int64_t>{1}, fpr, value).IsOk()) << "fpr " << fpr;
    }
}
